let gameSeq = [];       // Random Sequence generated by game
let userSeq = [];       // Sequence entered by the user

let h2 = document.querySelector('h2'); // Selecting H2 where we will be updating the levels
let level = 0;                          // Initial Level
let start = false;                     // Game is not started yet
let divsToFlash = ['tl','bl','tr','br'] // Manually defining all Div based on Positon

let allDivs = document.querySelectorAll('.colorbox'); // Selecting All Divs to Flash

document.addEventListener('keypress',function(){    // Event Listener Looking for inital Keypress

  
    start = true;                                   // Game Started
    levelUp();                                      // Level 1 

})




function levelUp()
{
    userSeq = [];
    level++;
    h2.innerText = `Level ${level}`;
    
    randomColor();
}

function randomColor()
{
    let randomNumber = Math.floor(Math.random()*3)
    console.log(`Random Number is ${randomNumber}`);
    
    let randomDiv = allDivs[randomNumber];

    flashDiv(randomDiv);
}

function flashDiv(btn)
{
    btn.classList.add("flash");
    console.log(btn.classList[1]);
    
    setTimeout(function(){btn.classList.remove("flash")},500);
    gameSeq.push(btn.classList[1]);
    console.log(gameSeq);
}

for (div of allDivs)
    {
        div.addEventListener("click",userInput)
           
    }
    


function userInput(div)
{
   let udiv = this;
   UserflashDiv(udiv)
}

function UserflashDiv(btn)      
{
    btn.classList.add("userFlash");
    setTimeout(function(){btn.classList.remove("userFlash")},500);
    userSeq.push(btn.classList[1]);
    checkAns(userSeq.length-1)
}


function checkAns(idx)
{
    
    
    if(gameSeq[idx] == userSeq[idx])
    {
        if(gameSeq.length == userSeq.length)
        {
            setTimeout(levelUp, 1000);
        }
    }
    else
    {
        let body = document.querySelector('body');
        body.style.backgroundColor = "red"
        h2.innerText = "Game Over. Press any key to play again"
        level = 0;
        start = false;
        gameSeq = 0;
        userSeq = 0;
        
    }
}
